# Generated by Django 5.0.1 on 2024-01-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0002_alter_outlet_no_telpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='slug',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
