# Generated by Django 5.0.1 on 2024-01-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0003_outlet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='no_telpn',
            field=models.CharField(max_length=14),
        ),
    ]
