# Generated by Django 5.0.1 on 2024-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0004_alter_outlet_no_telpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='endpoin',
            field=models.CharField(unique=True),
        ),
    ]
