# Generated by Django 5.0.1 on 2024-01-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='usr',
            name='no_telpn',
            field=models.CharField(default=0, max_length=14, unique=True),
        ),
    ]
